version: '3.4'

services:
  eshopdb:
    image: postgres
    container_name: eshopdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=EShopDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data/
  
  distributedCache:
    image: redis
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"
      
  messagebus:
    image: rabbitmq:management
    container_name: messagebus
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    
  identity:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://eshopdb/EShopDb?currentSchema=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=12345
    restart: always
    ports:
      - "9090:8080"
    command:
      - start-dev
    
    
volumes:
  postgres_eshopdb: