version: '3.4'

services:
  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=EShopDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data/